using System.Collections.Generic;
using System.Threading.Tasks;
using Fr8Data.Control;
using Fr8Data.DataTransferObjects;
using Fr8Data.Manifests;
using Fr8Data.States;
using StructureMap;
using terminalFr8Core.Infrastructure;
using terminalFr8Core.Interfaces;
using terminalUtilities.Infrastructure;
using terminalUtilities.Interfaces;
using terminalUtilities.Models;
using TerminalBase.BaseClasses;
using Utilities.Configuration.Azure;

namespace terminalFr8Core.Activities
{
    public class Send_Email_v1 : EnhancedTerminalActivity<Send_Email_v1.ActivityUi>
    {
        public static ActivityTemplateDTO ActivityTemplateDTO = new ActivityTemplateDTO
        {
            Name = "Send_Email",
            Label = "Send Email using Fr8 core account",
            Version = "1",
            Category = ActivityCategory.Forwarders,
            NeedsAuthentication = false,
            MinPaneWidth = 400,
            WebService = TerminalData.WebServiceDTO,
            Terminal = TerminalData.TerminalDTO
        };
        protected override ActivityTemplateDTO MyTemplate => ActivityTemplateDTO;

        private readonly IEmailPackager _emailPackager;

        public class ActivityUi : StandardConfigurationControlsCM
        {
            public TextSource EmailAddress { get; set; }
            public TextSource EmailSubject { get; set; }
            public TextSource EmailBody { get; set; }

            public ActivityUi()
            {
                EmailAddress = new TextSource("Email Address", string.Empty, nameof(EmailAddress))
                {
                    Source = new FieldSourceDTO
                    {
                        Label = string.Empty,
                        ManifestType = CrateManifestTypes.StandardDesignTimeFields,
                        FilterByTag = string.Empty,
                        RequestUpstream = true
                    }
                };
                EmailAddress.Events.Add(new ControlEvent("onChange", "requestConfig"));

                EmailSubject = new TextSource("Email Subject", string.Empty, nameof(EmailSubject))
                {
                    Source = new FieldSourceDTO
                    {
                        Label = string.Empty,
                        ManifestType = CrateManifestTypes.StandardDesignTimeFields,
                        FilterByTag = string.Empty,
                        RequestUpstream = true
                    }
                };
                EmailSubject.Events.Add(new ControlEvent("onChange", "requestConfig"));

                EmailBody = new TextSource("Email Body", string.Empty, nameof(EmailBody))
                {
                    Source = new FieldSourceDTO
                    {
                        Label = string.Empty,
                        ManifestType = CrateManifestTypes.StandardDesignTimeFields,
                        FilterByTag = string.Empty,
                        RequestUpstream = true
                    }
                };
                EmailBody.Events.Add(new ControlEvent("onChange", "requestConfig"));

                Controls = new List<ControlDefinitionDTO> { EmailAddress, EmailSubject, EmailBody };
            }
        }

        public Send_Email_v1() : base(false)
        {
            _emailPackager = ObjectFactory.GetInstance<IEmailPackager>();
        }

        protected override Task InitializeETA()
        {
            return Task.FromResult(0);
        }

        protected override Task ConfigureETA()
        {
            return Task.FromResult(0);
        }

        protected override async Task RunETA()
        {
            var fromAddress = CloudConfigurationManager.GetSetting("OutboundFromAddress");

            var emailAddress = ActivityUI.EmailAddress.GetValue(Payload);
            var emailSubject = ActivityUI.EmailSubject.GetValue(Payload);
            var emailBody = ActivityUI.EmailBody.GetValue(Payload);

            var userData = await GetCurrentUserData();
            var footerMessage = string.Format(@"<hr> <p> This email was generated by The Fr8 Company as part of the processing of Fr8 Container {0} on behalf of Fr8 User 
                                {1}.For questions about this email or other Fr8 matters, go to www.fr8.co </p>",
                                ExecutionContext.ContainerId, userData.FirstName + " " + userData.LastName);

            var mailerDO = new TerminalMailerDO()
            {
                Email = new EmailDTO()
                {
                    From = new EmailAddressDTO
                    {
                        Address = fromAddress,
                        Name = "Fr8 Operations"
                    },
                    Recipients = new List<RecipientDTO>()
                    {
                        new RecipientDTO()
                        {
                            EmailAddress = new EmailAddressDTO(emailAddress),
                            EmailParticipantType = EmailParticipantType.To
                        }
                    },
                    Subject = emailSubject,
                    HTMLText = CreateEmailHTMLText(emailBody)
                },
                Footer = footerMessage,
            };
            await _emailPackager.Send(mailerDO);
            Success();
        }

        private string CreateEmailHTMLText(string emailBody)
        {
            var template = @"<html><body>{0}</body></html>";
            var htmlText = string.Format(template, emailBody);

            return htmlText;
        }
    }
}