/// <reference path="../typings/tsd.d.ts" />
/// <reference path="services/processtemplateservice.ts" />
/// <reference path="interfaces/iprocesstemplatevm.ts" />
/// <reference path="../typings/metronic.d.ts" />
/// <reference path="services/stringservice.ts" />
/// <reference path="services/stringservice.ts" />
/// <reference path="filters/processtemplatestate.ts" />
/// <reference path="controllers/processtemplatescontroller.ts" />
//# sourceMappingURL=_all.js.map