// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class EmailDO_AddDateCreated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EmailDO_AddDateCreated));
        
        string IMigrationMetadata.Id
        {
            get { return "201406111328209_EmailDO_AddDateCreated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
