// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class rename_Kacts_to_Facts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rename_Kacts_to_Facts));
        
        string IMigrationMetadata.Id
        {
            get { return "201407100603524_rename_Kacts_to_Facts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
