// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class change_datetime_to_offset_Fact : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_datetime_to_offset_Fact));
        
        string IMigrationMetadata.Id
        {
            get { return "201407110934086_change_datetime_to_offset_Fact"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
