// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Sync01072014 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Sync01072014));
        
        string IMigrationMetadata.Id
        {
            get { return "201407010743506_Sync-01.07.2014"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
