// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Add_InvitationDO : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_InvitationDO));
        
        string IMigrationMetadata.Id
        {
            get { return "201408130809305_Add_InvitationDO"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
