// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Sync25062014 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Sync25062014));
        
        string IMigrationMetadata.Id
        {
            get { return "201406251552253_Sync-25.06.2014"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
