// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Sync04082014 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Sync04082014));
        
        string IMigrationMetadata.Id
        {
            get { return "201408041322379_Sync.04.08.2014"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
