// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class SyncRob06122014 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SyncRob06122014));
        
        string IMigrationMetadata.Id
        {
            get { return "201412061448191_Sync.Rob.06.12.2014"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
