// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Add_State_to_UserDO : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_State_to_UserDO));
        
        string IMigrationMetadata.Id
        {
            get { return "201410311036361_Add_State_to_UserDO"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
