// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddCalendarLastSynchronized : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCalendarLastSynchronized));
        
        string IMigrationMetadata.Id
        {
            get { return "201407111624232_AddCalendarLastSynchronized"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
