// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class _201508282028_ChangedActionListActionDO : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201508282028_ChangedActionListActionDO));
        
        string IMigrationMetadata.Id
        {
            get { return "201508281126398_201508282028_ChangedActionListActionDO"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
