// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class _201508202025_ActionListDOActionDo_ActionState : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201508202025_ActionListDOActionDo_ActionState));
        
        string IMigrationMetadata.Id
        {
            get { return "201508201325363_201508202025_ActionListDOActionDo_ActionState"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
