// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class _201509101040_ProcessDO_AddedCurrentAndNextActivity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201509101040_ProcessDO_AddedCurrentAndNextActivity));
        
        string IMigrationMetadata.Id
        {
            get { return "201509100242590_201509101040_ProcessDO_AddedCurrentAndNextActivity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
