// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class RouteDO_Tag : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RouteDO_Tag));
        
        string IMigrationMetadata.Id
        {
            get { return "201511170753503_RouteDO_Tag"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
