namespace Data.Migrations
{
    using System;
    using System.Data.Entity.Migrations;

    public partial class FillManifestRegistry : System.Data.Entity.Migrations.DbMigration
    {
        public override void Up()
        {

            Sql(@"
DECLARE @StringTypeId uniqueidentifier;

SELECT @StringTypeId = Id FROM MtTypes WHERE ClrName = 'System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089';
IF (@StringTypeId IS NULL)
BEGIN
	SET @StringTypeId = NEWID();
	INSERT INTO MtTypes (Id, Alias, ClrName, IsPrimitive, IsComplex, ManifestId) 
	VALUES (@StringTypeId, NULL, 'System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089', 1, 0, NULL);
END;

DECLARE @CrateManifestTypeId uniqueidentifier;
SELECT @CrateManifestTypeId = Id FROM MtTypes WHERE ClrName = 'Fr8.Infrastructure.Data.Crates.CrateManifestType, Fr8Infrastructure.NET, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null';
IF (@CrateManifestTypeId IS NULL)
BEGIN
	SET @CrateManifestTypeId = NEWID();
	INSERT INTO MtTypes (Id, Alias, ClrName, IsPrimitive, IsComplex, ManifestId) 
	VALUES (@CrateManifestTypeId, NULL, 'Fr8.Infrastructure.Data.Crates.CrateManifestType, Fr8Infrastructure.NET, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null', 0, 1, NULL);
END;

DECLARE @ManifestTypeId uniqueidentifier;

SELECT @ManifestTypeId = Id FROM MtTypes WHERE Alias = 'Manifest Description';

IF (@ManifestTypeId IS NULL)
BEGIN
	SET @ManifestTypeId = NEWID();
	INSERT INTO MtTypes (Id, Alias, ClrName, IsPrimitive, IsComplex, ManifestId) 
	VALUES (@ManifestTypeId, 'Manifest Description', 'Fr8Data.Manifests.ManifestDescriptionCM, Fr8Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null', 0, 0, 30);

	INSERT INTO MtProperties (Name, Offset, Type, DeclaringType) VALUES ('Id', 0, @StringTypeId, @ManifestTypeId);
	INSERT INTO MtProperties (Name, Offset, Type, DeclaringType) VALUES ('Name', 1, @StringTypeId, @ManifestTypeId);
	INSERT INTO MtProperties (Name, Offset, Type, DeclaringType) VALUES ('Version', 2, @StringTypeId, @ManifestTypeId);
	INSERT INTO MtProperties (Name, Offset, Type, DeclaringType) VALUES ('SampleJSON', 3, @StringTypeId, @ManifestTypeId);
	INSERT INTO MtProperties (Name, Offset, Type, DeclaringType) VALUES ('Description', 4, @StringTypeId, @ManifestTypeId);
	INSERT INTO MtProperties (Name, Offset, Type, DeclaringType) VALUES ('RegisteredBy', 5, @StringTypeId, @ManifestTypeId);
	INSERT INTO MtProperties (Name, Offset, Type, DeclaringType) VALUES ('ManifestType', 6, @CrateManifestTypeId, @ManifestTypeId);
END;

DELETE FROM MtData WHERE Type = @ManifestTypeId;

INSERT INTO MtData (Type, CreatedAt, UpdatedAt, fr8AccountId, IsDeleted, Value1, Value2, Value3, Value4, Value5, Value6, Value7) 
VALUES (@ManifestTypeId, SYSDATETIME(), SYSDATETIME(), 'system1@fr8.co', 0, '3', 'FieldDescriptionsCM', '1', 
'{
	""fields"": [

        {
                ""key"": ""JIRA description"",
			""value"": null,
			""label"": null,
			""fieldType"": null,
			""isRequired"": false,
			""availability"": 2,
			""sourceCrateLabel"": ""Message Built by \""Build Message\"" Activity"",
			""sourceActivityId"": ""8431df33-134f-4ba3-bda0-9c0f5257f232""

        }
	]
}'
, 'Stores the collection of fields', 'Fr8', '{""Type"" : ""Manifest Description"", ""Id"" : 30}');

INSERT INTO MtData(Type, CreatedAt, UpdatedAt, fr8AccountId, IsDeleted, Value1, Value2, Value3, Value4, Value5, Value6, Value7)
VALUES(@ManifestTypeId, SYSDATETIME(), SYSDATETIME(), 'system1@fr8.co', 0, '5', 'StandardPayloadDataCM', '1', 
'{
	""name"" : ""Payload Crate"",
	""objectType"" : ""PayloadType"",
	""payloadObjects"" : [
		{
			""fields"" : [
			{
				""key"": ""JIRA description"",
				""value"": null,
				""label"": null,
				""fieldType"": null,
				""isRequired"": false,
				""availability"": 2,
				""sourceCrateLabel"": ""Message Built by \""Build Message\"" Activity"",
				""sourceActivityId"": ""8431df33-134f-4ba3-bda0-9c0f5257f232""

            }
			]
		}
	]
}'
, 'Represents a paylod generated by activity at execution stage', 'Fr8', '{""Type"" : ""Manifest Description"", ""Id"" : 30}');

INSERT INTO MtData(Type, CreatedAt, UpdatedAt, fr8AccountId, IsDeleted, Value1, Value2, Value3, Value4, Value5, Value6, Value7)
VALUES(@ManifestTypeId, SYSDATETIME(), SYSDATETIME(), 'system1@fr8.co', 0, '6', 'StandardConfigurationControlsCM', '1', 
'{
	""Controls"": [
		{
			""listItems"": [
				{
					""selected"": false,
					""key"": ""Manifest Submission Form"",
					""value"": ""1Uc8-_qLmYl3dMs8v8fDlEjPbsO7HfZz6ugReNKq-XmY""
				},
				{
					""selected"": false,
					""key"": ""Volunteer Sign Up Form (Team Rubicon)"",
					""value"": ""1-K0Z2dhRQNYt4DFeNA6oX86FybTrgVe3Ed8nC7m3KPA""
				}
			],
			""selectedKey"": ""Manifest Submission Form"",
			""hasRefreshButton"": false,
			""selectedItem"": null,
			""name"": ""Selected_Google_Form"",
			""required"": true,
			""value"": ""1Uc8-_qLmYl3dMs8v8fDlEjPbsO7HfZz6ugReNKq-XmY"",
			""label"": ""Select Google Form"",
			""type"": ""DropDownList"",
			""selected"": false,
			""events"": [
				{
					""name"": ""onChange"",
					""handler"": ""requestConfig""
				}
			],
			""source"": null,
			""showDocumentation"": null,
			""isHidden"": false,
			""isCollapsed"": false
		}
	]
}'
, 'Represents a set of controls that comprise the UI of activity', 'Fr8', '{""Type"" : ""Manifest Description"", ""Id"" : 30}');

INSERT INTO MtData(Type, CreatedAt, UpdatedAt, fr8AccountId, IsDeleted, Value1, Value2, Value3, Value4, Value5, Value6, Value7)
VALUES(@ManifestTypeId, SYSDATETIME(), SYSDATETIME(), 'system1@fr8.co', 0, '7', 'EventReportCM', '1', 
'{
	""eventNames"" : ""Processed, Failed"",
	""containerDoId"" : ""8431df33-134f-4ba3-bda0-9c0f5257f232"",
	""externalAccountId"" : ""example@example.com"",
	""externalDomainId"" : """",
	""eventPayload"" : [
		{
			""manifestType"": ""Standard UI Controls"",
            ""manifestId"": 6,
            ""manufacturer"": null,
            ""manifestRegistrar"": ""fr8.co/registry"",
            ""id"": ""0eb2f713-55d3-4d12-bb90-d6a32228205d""
		}
	]
	""manufacturer"" : ""Fr8"",
	""Source"" : ""Activity_Name""
}'
, 'Represents a packed data of extenal event that terminal sends to hub', 'Fr8', '{""Type"" : ""Manifest Description"", ""Id"" : 30}');

INSERT INTO MtData(Type, CreatedAt, UpdatedAt, fr8AccountId, IsDeleted, Value1, Value2, Value3, Value4, Value5, Value6, Value7)
VALUES(@ManifestTypeId, SYSDATETIME(), SYSDATETIME(), 'system1@fr8.co', 0, '8', 'EventSubscriptionCM', '1', 
'{
	""subscriptions"" : [
		""Processed"",
		""Failed""
	],
	""manufacturer"" : ""Fr8""
}'
, 'Represents a terminal subscriptions to events received from external services', 'Fr8', '{""Type"" : ""Manifest Description"", ""Id"" : 30}');

INSERT INTO MtData(Type, CreatedAt, UpdatedAt, fr8AccountId, IsDeleted, Value1, Value2, Value3, Value4, Value5, Value6, Value7)
VALUES(@ManifestTypeId, SYSDATETIME(), SYSDATETIME(), 'system1@fr8.co', 0, '9', 'StandardTableDataCM', '1', 
'{
	""Table"": [
		{
			""Row"": [
				{
					""Cell"": {
						""key"": ""names"",
						""value"": ""names"",
						""label"": null,
						""fieldType"": null,
						""isRequired"": false
					}
				},
				{
					""Cell"": {
						""key"": ""company"",
						""value"": ""company"",
						""label"": null,
						""fieldType"": null,
						""isRequired"": false
					}
				},
				{
					""Cell"": {
						""key"": ""title"",
						""value"": ""title"",
						""label"": null,
						""fieldType"": null,
						""isRequired"": false
						}
				},
				{
					""Cell"": {
						""key"": ""date"",
						""value"": ""date"",
						""label"": null,
						""fieldType"": null,
						""isRequired"": false
					}
				}
			]
		}
	],
	""FirstRowHeaders"": true,
	""HasDataRows"": true
}', 'Represents data packed into table form', 'Fr8', '{""Type"" : ""Manifest Description"", ""Id"" : 30}');

INSERT INTO MtData(Type, CreatedAt, UpdatedAt, fr8AccountId, IsDeleted, Value1, Value2, Value3, Value4, Value5, Value6, Value7)
VALUES(@ManifestTypeId, SYSDATETIME(), SYSDATETIME(), 'system1@fr8.co', 0, '10', 'StandardFileDescriptionCM', '1', 
'{
	""directUrl"" : ""http://example.com/example.pdf"",
	""fileName"" : ""example.pdf"",
	""fileType"" : ""pdf"",
	""textRepresentation: """"
}', 'Contains information about file', 'Fr8', '{""Type"" : ""Manifest Description"", ""Id"" : 30}');

INSERT INTO MtData(Type, CreatedAt, UpdatedAt, fr8AccountId, IsDeleted, Value1, Value2, Value3, Value4, Value5, Value6, Value7)
VALUES(@ManifestTypeId, SYSDATETIME(), SYSDATETIME(), 'system1@fr8.co', 0, '12', 'StandardAuthenticationCM', '1', 
'{
	 ""mode"" : 1,
	 ""revocation"" : true
}', 'Intstructs hub to perform authentication of user for the given terminal', 'Fr8', '{""Type"" : ""Manifest Description"", ""Id"" : 30}');

INSERT INTO MtData(Type, CreatedAt, UpdatedAt, fr8AccountId, IsDeleted, Value1, Value2, Value3, Value4, Value5, Value6, Value7)
VALUES(@ManifestTypeId, SYSDATETIME(), SYSDATETIME(), 'system1@fr8.co', 0, '13', 'StandardLoggingCM', '1', 
'{
	 ""loggingMTkey"" : ""0eb2f713-55d3-4d12-bb90-d6a32228205d"",
	 ""item"" : [
		{
			 ""name"" : ""name"",
			 ""primaryCategory"" : ""AuthToken"",
			 ""secondaryCategory"" : ""Created"",
			 ""activity"" : ""AuthToken created"",
			 ""data"" : """",
			 ""isLogged"" : true,
			 ""status"" : """",
			 ""customerId"" : ""0eb2f713-55d3-4d12-bb90-d6a32228205d"",
			 ""objectId"" : ""0eb2gyt1-g6d3-50lm-bb90-d6a32228205d"",
			 ""lastUpdated"" : ""2016-01-01 10:00:00"",
			 ""createDate"" : ""2016-01-01 10:00:00"",
			 ""discriminator"" : Incident"",
			 ""priority"" : 1,
			 ""manufacturer"" : ""Fr8"",
			 ""type"" : ""Terminal""
		}
	 ]
}', 'Contains information about log entry', 'Fr8', '{""Type"" : ""Manifest Description"", ""Id"" : 30}');

INSERT INTO MtData(Type, CreatedAt, UpdatedAt, fr8AccountId, IsDeleted, Value1, Value2, Value3, Value4, Value5, Value6, Value7)
VALUES(@ManifestTypeId, SYSDATETIME(), SYSDATETIME(), 'system1@fr8.co', 0, '10013', 'LoggingDataCM', '1', 
'{
	 
	""objectId"" : ""0eb2f713-55d3-4d12-bb90-d6a32228205d"",
	""primaryCategory"" : ""AuthToken"",
	""secondaryCategory"" : ""Created"",
	""activity"" : ""AuthToken created"",
	""data"" : """",
	""fr8UserId"" : ""0eb2gyt1-g6d3-50lm-bb90-d6a32228205d""
		
}', 'Contains information about log entry', 'Fr8', '{""Type"" : ""Manifest Description"", ""Id"" : 30}');

INSERT INTO MtData(Type, CreatedAt, UpdatedAt, fr8AccountId, IsDeleted, Value1, Value2, Value3, Value4, Value5, Value6, Value7)
VALUES(@ManifestTypeId, SYSDATETIME(), SYSDATETIME(), 'system1@fr8.co', 0, '14', 'DocuSignEventCM', '1', 
'{
	""object"" : ""Envelope"",
	""status"" : ""Received"",
	""eventId"" : ""0eb2gyt1-g6d3-50lm-bb90-d6a32228205d"",
	""envelopeId"" : ""0eb2f713-55d3-4d12-bb90-d6a32228205d"",
	""recipientId"" : ""0eb2f713-55d3-4d12-bb90-d6a32228205d"",
	""externalAccountId"" : ""example@example.com""
}', 'Contains information about DocuSign event', 'Fr8', '{ ""Type"" : ""Manifest Description"", ""Id"" : 30}');

INSERT INTO MtData (Type, CreatedAt, UpdatedAt, fr8AccountId, IsDeleted, Value1, Value2, Value3, Value4, Value5, Value6, Value7) 
VALUES (@ManifestTypeId, SYSDATETIME(), SYSDATETIME(), 'system1@fr8.co', 0, '15', 'DocuSignEventCM', '1', 
'{
	""status"" : ""Received"",
	""createDate"" : ""2016-01-01 10:00:00"",
	""sendDate"" : ""2016-01-01 10:00:00"",
	""deliveredDate"" : ""2016-01-01 10:00:00"",
	""completedDate"" : ""2016-01-01 10:00:00"",
	""envelopeId"" : ""0eb2f713-55d3-4d12-bb90-d6a32228205d"",
	""externalAccountId"" : ""example@example.com""
	""name"" : ""Envelope Name"",
	""subject"" : ""Envelope Subject"",
	""ownerName"" : ""Owner Name"",
	""senderName"" : ""Sender Name"",
	""senderEmail"" : ""Sender Email"",
	""shared"" : ""true"",
	""statusChangeDateTime"" : ""2016-01-01 10:00:00""
}', 'Contains information about DocuSign envelope', 'Fr8', '{""Type"" : ""Manifest Description"", ""Id"" : 30}');

INSERT INTO MtData(Type, CreatedAt, UpdatedAt, fr8AccountId, IsDeleted, Value1, Value2, Value3, Value4, Value5, Value6, Value7)
VALUES(@ManifestTypeId, SYSDATETIME(), SYSDATETIME(), 'system1@fr8.co', 0, '17', 'StandardQueryCM', '1', 
'{
	""queries"" : [
		{
			""name"" : ""Query Name"",
			""filterConditions"" : [
				{
					""field"" : ""Id"",
					""operator"" : ""eq"",
					""value"" : ""123""
				}
			]
		}
	]
}', 'Contains information about one or more queries to data source', 'Fr8', '{""Type"" : ""Manifest Description"", ""Id"" : 30}');

INSERT INTO MtData(Type, CreatedAt, UpdatedAt, fr8AccountId, IsDeleted, Value1, Value2, Value3, Value4, Value5, Value6, Value7)
VALUES(@ManifestTypeId, SYSDATETIME(), SYSDATETIME(), 'system1@fr8.co', 0, '19', 'StandardFr8PlansCM', '1', 
'{
	""createDate"" : ""2016-01-01 10:00:00"",
	""lastUpdated"" : ""2016-01-01 10:00:00"",
	""description"" : ""description"",
	""name"" : ""name"",
	""ordering"" : 1,
	""planState"" : ""ready"",
	""subPlans"" : [
		{
			""subPlanId"" : ""0eb2f713-55d3-4d12-bb90-d6a32228205d"",
			""planId"" : ""0eb2f713-55d3-4d12-bb90-d6a32228205d"",
			""parentId"" : ""0eb2f713-55d3-4d12-bb90-d6a32228205d"",
			""name"" : ""sub plan name""
		}
	]
}', 'Contains information about Fr8 plan', 'Fr8', '{""Type"" : ""Manifest Description"", ""Id"" : 30}');

INSERT INTO MtData(Type, CreatedAt, UpdatedAt, fr8AccountId, IsDeleted, Value1, Value2, Value3, Value4, Value5, Value6, Value7)
VALUES(@ManifestTypeId, SYSDATETIME(), SYSDATETIME(), 'system1@fr8.co', 0, '20', 'StandardFr8HubsCM', '1', 
'{
	""name"" : ""Hub"",
	""description"" : ""description"",
	""createdDate"" : ""2016-01-01 10:00:00"",
	""lastUpdated"" : ""2016-01-01 10:00:00""
}', 'Contains information about Fr8 hub', 'Fr8', '{""Type"" : ""Manifest Description"", ""Id"" : 30}');

INSERT INTO MtData(Type, CreatedAt, UpdatedAt, fr8AccountId, IsDeleted, Value1, Value2, Value3, Value4, Value5, Value6, Value7)
VALUES(@ManifestTypeId, SYSDATETIME(), SYSDATETIME(), 'system1@fr8.co', 0, '21', 'StandardFr8ContainersCM', '1', 
'{
	""name"" : ""Container"",
	""description"" : ""description"",
	""createdDate"" : ""2016-01-01 10:00:00"",
	""lastUpdated"" : ""2016-01-01 10:00:00""
}', 'Contains information about Fr8 container', 'Fr8', '{""Type"" : ""Manifest Description"", ""Id"" : 30}');

INSERT INTO MtData(Type, CreatedAt, UpdatedAt, fr8AccountId, IsDeleted, Value1, Value2, Value3, Value4, Value5, Value6, Value7)
VALUES(@ManifestTypeId, SYSDATETIME(), SYSDATETIME(), 'system1@fr8.co', 0, '23', 'StandardFr8TerminalCM', '1', 
'{
	""definition"" : {
		""name"" : ""Terminal Name"",
		""label"" : ""Terminal Label"",
		""version"" : ""1"",
		""terminalStatus"" : ""Active"",
		""endpoint"" : ""http://example.com:8080"",
		""description"" : ""Some description"",
		""authenticationType"" : 1
	}
	""activities"" : [
		{
			""id"" : ""0eb2f713-55d3-4d12-bb90-d6a32228205d"",
			""name"" : ""Name"",
			""label"" : ""Label"",
			""version"" : ""1"",
			""tags"" : ""Tags"",
			""category"" : ""Forwarders"",
			""type"" : ""Activity"",
			""needsAuthentication"" : true
		}
	]
}', 'Contains information about Fr8 terminal', 'Fr8', '{""Type"" : ""Manifest Description"", ""Id"" : 30}');

INSERT INTO MtData(Type, CreatedAt, UpdatedAt, fr8AccountId, IsDeleted, Value1, Value2, Value3, Value4, Value5, Value6, Value7)
VALUES(@ManifestTypeId, SYSDATETIME(), SYSDATETIME(), 'system1@fr8.co', 0, '24', 'StandardFileListCM', '1', 
'{
	""fileList"" : [
		{
			""directUrl"" : ""http://example.com/example.pdf"",
			""fileName"" : ""example.pdf"",
			""fileType"" : ""pdf"",
			""textRepresentation: """"
		}
	]
}', 'Contains list of files', 'Fr8', '{""Type"" : ""Manifest Description"", ""Id"" : 30}');

INSERT INTO MtData(Type, CreatedAt, UpdatedAt, fr8AccountId, IsDeleted, Value1, Value2, Value3, Value4, Value5, Value6, Value7)
VALUES(@ManifestTypeId, SYSDATETIME(), SYSDATETIME(), 'system1@fr8.co', 0, '25', 'StandardAccountingTransactionCM', '1', 
'{
	""accountingTransactions"" : [
		{
			""name"" : ""Name"",
			""transactionDate"" : ""2016-01-01 10:00:00"",
			""memo"" : ""Some text"",
			""financialLines"" : [
				{
					""amount"" : ""100"",
					""accountName"" : ""Account Name"",
					""accountId"" : ""1234567890"",
					""debitOrCredit"" : ""Debit"",
					""description"" : ""Description""
				}
			]
		}
	]
}', 'Contains list of accounting transactions', 'Fr8', '{""Type"" : ""Manifest Description"", ""Id"" : 30}');

INSERT INTO MtData(Type, CreatedAt, UpdatedAt, fr8AccountId, IsDeleted, Value1, Value2, Value3, Value4, Value5, Value6, Value7)
VALUES(@ManifestTypeId, SYSDATETIME(), SYSDATETIME(), 'system1@fr8.co', 0, '26', 'DocuSignRecipientCM', '1', 
'{
	""object"" : ""Envelope"",
	""status"" : ""Signed"",
	""docuSignAccountId"" : ""0eb2f713-55d3-4d12-bb90-d6a32228205d"",
	""recipientId"" : ""0eb2f713-55d3-4d12-bb90-d6a32228205d"",
	""recipientEmail"" : ""example@example.com"",
	""envelopeId"" : ""0eb2f713-55d3-4d12-bb90-d6a32228205d""
}', 'Contains information about DocuSign recipient', 'Fr8', '{""Type"" : ""Manifest Description"", ""Id"" : 30}');

INSERT INTO MtData(Type, CreatedAt, UpdatedAt, fr8AccountId, IsDeleted, Value1, Value2, Value3, Value4, Value5, Value6, Value7)
VALUES(@ManifestTypeId, SYSDATETIME(), SYSDATETIME(), 'system1@fr8.co', 0, '27', 'OperationalStateCM', '1', 
'{
	""activityCallStack"" : {
		""stack"" : [
			{
				""nodeId"" : ""0eb2f713-55d3-4d12-bb90-d6a32228205d"",
				""nodeName"" : ""Some Name"",
				""activityExecutionPhase"" : 0,
				""currentChildId"" : ""0eb2f713-55d3-4d12-bb90-d6a32228205d"",
				""localData"" : [

                    ...

                ]
			}			
		],
		""history"" : [
			{
				""description"" : ""Description""
			}
		],

		""currentActivityResponse"" : {
			""type"" : ""Erorr"",
			""body"" : ""Error Message""
		}
	}
}', 'Contains information that hub uses to control the execution flow of the plan', 'Fr8', '{""Type"" : ""Manifest Description"", ""Id"" : 30}');

INSERT INTO MtData(Type, CreatedAt, UpdatedAt, fr8AccountId, IsDeleted, Value1, Value2, Value3, Value4, Value5, Value6, Value7)
VALUES(@ManifestTypeId, SYSDATETIME(), SYSDATETIME(), 'system1@fr8.co', 0, '28', 'DocuSignTemplateCM', '1', 
'{
	""status"" : ""Active"",
	""createDate"" : ""2016-01-01 10:00:00"",
	""body"" : ""Body"",
	""name"" : ""Name""
}', 'Contains information about DocuSign template', 'Fr8', '{""Type"" : ""Manifest Description"", ""Id"" : 30}');

INSERT INTO MtData(Type, CreatedAt, UpdatedAt, fr8AccountId, IsDeleted, Value1, Value2, Value3, Value4, Value5, Value6, Value7)
VALUES(@ManifestTypeId, SYSDATETIME(), SYSDATETIME(), 'system1@fr8.co', 0, '29', 'ChartOfAccountsCM', '1', 
'{
	""accounts"" : [
		{
			""id"" : ""0eb2f713-55d3-4d12-bb90-d6a32228205d"",
			""name"" : ""Account Name""
		}
	]
}', 'Contains information about account list', 'Fr8', '{""Type"" : ""Manifest Description"", ""Id"" : 30}');

INSERT INTO MtData(Type, CreatedAt, UpdatedAt, fr8AccountId, IsDeleted, Value1, Value2, Value3, Value4, Value5, Value6, Value7)
VALUES(@ManifestTypeId, SYSDATETIME(), SYSDATETIME(), 'system1@fr8.co', 0, '30', 'ManifestDescriptionCM', '1', 
'{
	""id"" : ""1"",
	""name"" : ""SomeManifestCM"",
	""version"" : ""1"",
	""sampleJson"" : ""{ ""name"" : ""value"" }"",
	""description"" : ""Description"",
	""registeredBy"" : ""Fr8""
}', 'Contains information about description of manifest contents', 'Fr8', '{""Type"" : ""Manifest Description"", ""Id"" : 30}');

INSERT INTO MtData(Type, CreatedAt, UpdatedAt, fr8AccountId, IsDeleted, Value1, Value2, Value3, Value4, Value5, Value6, Value7)
VALUES(@ManifestTypeId, SYSDATETIME(), SYSDATETIME(), 'system1@fr8.co', 0, '32', 'CrateDescriptionCM', '1', 
'{
	""crateDescriptions"" :[
		{
			""manifestId"" : ""1"",
			""manifestType"" : ""SomeManifestCM"",
			""label"" : ""Crate Label"",
			""producedBy"" : ""ActivityName"",
			""availability"" : ""Runtime"",
			""fields"" : [
				{
					""key"" : ""Key"",
					""value"" : ""Value""
			]
		}
	]
}', 'Contains information about crates and fields that activity expects to produce at runtime', 'Fr8', '{""Type"" : ""Manifest Description"", ""Id"" : 30}');

INSERT INTO MtData(Type, CreatedAt, UpdatedAt, fr8AccountId, IsDeleted, Value1, Value2, Value3, Value4, Value5, Value6, Value7)
VALUES(@ManifestTypeId, SYSDATETIME(), SYSDATETIME(), 'system1@fr8.co', 0, '34', 'ExternalObjectHandlesCM', '1', 
'{
	""handles"" :[
		{
			""name"" : ""Name"",
			""description"" : ""Description"",
			""manifestType"" : ""CrateDescriptionCM"",
			""directUrl"" : ""http://example.com/somehandle?id=1""
		}
	]
}', 'Contains information about external object handlers', 'Fr8', '{""Type"" : ""Manifest Description"", ""Id"" : 30}');

INSERT INTO MtData(Type, CreatedAt, UpdatedAt, fr8AccountId, IsDeleted, Value1, Value2, Value3, Value4, Value5, Value6, Value7)
VALUES(@ManifestTypeId, SYSDATETIME(), SYSDATETIME(), 'system1@fr8.co', 0, '35', 'SalesforceEventCM', '1', 
'{
	""objectType"" : ""Account"",
	""objectId"" : ""0eb2f713-55d3-4d12-bb90-d6a32228205d"",
	""createdDate"" : ""2016-01-01 10:00:00"",
	""lastModifiedDate"" : ""2016-01-01 10:00:00"",
	""occuredEvent"" : ""Created""
}', 'Contains information about external events received from Salesforce.com', 'Fr8', '{ ""Type"" : ""Manifest Description"", ""Id"" : 30}');

INSERT INTO MtData(Type, CreatedAt, UpdatedAt, fr8AccountId, IsDeleted, Value1, Value2, Value3, Value4, Value5, Value6, Value7)
VALUES(@ManifestTypeId, SYSDATETIME(), SYSDATETIME(), 'system1@fr8.co', 0, '36', 'DocuSignEnvelopeCM', '2', 
'{
	""envelopeId"" : ""0eb2f713-55d3-4d12-bb90-d6a32228205d"",
	""status"" : ""Signed"",
	""subject"" : ""Subject"",
	""statusChangedDateTime"" : ""2016-01-01 10:00:00"",
	""currentRoutingOrderId"" : ""0eb2f713-55d3-4d12-bb90-d6a32228205d"",
	""recipients"" : [
		{
			""type"" : ""Type"",
			""name"" : ""Mr X"",
			""email"" : ""example@example.com"",
			""recipientId"" : ""0eb2f713-55d3-4d12-bb90-d6a32228205d"",
			""routingOrderId"" : ""0eb2f713-55d3-4d12-bb90-d6a32228205d"",
			""status"" : ""Pending""
		},
	]
	""templates"" : [
		{
			""templateId"" : ""0eb2f713-55d3-4d12-bb90-d6a32228205d"",
			""name"" : ""Some Name"",
			""documentId"" : ""0eb2f713-55d3-4d12-bb90-d6a32228205d""
		}
	],
	""externalAccountId"" : ""example@example.com"",
	""createDate"" : ""2016-01-01 10:00:00"",
	""sentDate"" : ""2016-01-01 10:00:00""
}', 'Contains information about DocuSign envelope', 'Fr8', '{""Type"" : ""Manifest Description"", ""Id"" : 30}');

INSERT INTO MtData(Type, CreatedAt, UpdatedAt, fr8AccountId, IsDeleted, Value1, Value2, Value3, Value4, Value5, Value6, Value7)
VALUES(@ManifestTypeId, SYSDATETIME(), SYSDATETIME(), 'system1@fr8.co', 0, '37', 'StandardBusinessFactCM', '1', 
'{
	""userType"" : ""Owner"",
	""primaryCategory"" : ""AuthToken"",
	""secondaryCategory"" : ""Created"",
	""activity"" : ""AuthToken created"",
	""data"" : """",
	""status"" : """",
	""customerId"" : ""0eb2f713-55d3-4d12-bb90-d6a32228205d"",
	""objectId"" : ""0eb2gyt1-g6d3-50lm-bb90-d6a32228205d"",
	""ownerId"" : ""0eb2f713-55d3-4d12-bb90-d6a32228205d"",
	""createDate"" : ""2016-01-01 10:00:00"",
	""dayBucket"" : ""2016-01-01 10:00:00"",
	""weekBucket"" : ""2016-01-01 10:00:00"",
	""monthBucket"" : ""2016-01-01 10:00:00"",
	""yearBucket"" : ""2016-01-01 10:00:00""
}', 'Contains information about any business logic related event', 'Fr8', '{ ""Type"" : ""Manifest Description"", ""Id"" : 30}');

INSERT INTO MtData (Type, CreatedAt, UpdatedAt, fr8AccountId, IsDeleted, Value1, Value2, Value3, Value4, Value5, Value6, Value7) 
VALUES (@ManifestTypeId, SYSDATETIME(), SYSDATETIME(), 'system1@fr8.co', 0, '39', 'ValidationResultsCM', '1', 
'{
	""validationResults"" : [
		{
			""controlNames"" : [ ""Name1"", ""Name2"" ],
			""errorMessage"" : ""Specified value is not allowed""
		}
	]
}', 'Contains information about activity validation errors that hub uses to check if activity method was executed correctly', 'Fr8', '{""Type"" : ""Manifest Description"", ""Id"" : 30}');

INSERT INTO MtData(Type, CreatedAt, UpdatedAt, fr8AccountId, IsDeleted, Value1, Value2, Value3, Value4, Value5, Value6, Value7)
VALUES(@ManifestTypeId, SYSDATETIME(), SYSDATETIME(), 'system1@fr8.co', 0, '40', 'DocuSignEnvelopeCM', '3', 
'{
	""envelopes"" : [
		{
			""status"" : ""Signed"",
			""description"" : ""Description"",
			""createDate"" : ""2016-01-01 10:00:00"",
			""sendDate"" : ""2016-01-01 10:00:00"",
			""completedDate"" : ""2016-01-01 10:00:00"",
			""envelopeId"" : ""0eb2f713-55d3-4d12-bb90-d6a32228205d"",
			""name"" : ""Name"",
			""subject"" : ""Some subject"",
			""ownerName"" : ""Mr X"",
			""senderName"" : ""Mr Y"",
			""senderEmail"" : ""example@example.com"",
			""shared"" : ""true"",
			""templateId"" : ""0eb2f713-55d3-4d12-bb90-d6a32228205d""
		}
	]
}', 'Contains information about list of DocuSign envelopes', 'Fr8', '{""Type"" : ""Manifest Description"", ""Id"" : 30}');");
        }

        public override void Down()
        {
            Sql(@"
DECLARE @ManifestTypeId uniqueidentifier;

SELECT @ManifestTypeId = Id FROM MtTypes WHERE Alias = 'Manifest Description';

IF (@ManifestTypeId IS NOT NULL)
BEGIN
    DELETE FROM MtData WHERE Type = @ManifestTypeId;
END;");
        }
    }
}
