// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class FasterMigrateMTData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FasterMigrateMTData));
        
        string IMigrationMetadata.Id
        {
            get { return "201603051236490_FasterMigrateMTData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
