// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Table_RolePrivilege : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Table_RolePrivilege));
        
        string IMigrationMetadata.Id
        {
            get { return "201603302057295_Table_RolePrivilege"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
