// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Update_QBIcon_Url : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_QBIcon_Url));
        
        string IMigrationMetadata.Id
        {
            get { return "201601011626284_Update_QBIcon_Url"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
