// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Standard_Permissions_for_Terminals : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Standard_Permissions_for_Terminals));
        
        string IMigrationMetadata.Id
        {
            get { return "201607310758516_Standard_Permissions_for_Terminals"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
