// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class FixManifestDescriptionTypos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixManifestDescriptionTypos));
        
        string IMigrationMetadata.Id
        {
            get { return "201607271152557_FixManifestDescriptionTypos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
