// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Container_Id_Int32_To_Guid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Container_Id_Int32_To_Guid));
        
        string IMigrationMetadata.Id
        {
            get { return "201511131623530_Container_Id_Int32_To_Guid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
