// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Renamed_PluginId_To_TerminalId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Renamed_PluginId_To_TerminalId));
        
        string IMigrationMetadata.Id
        {
            get { return "201511021809221_Renamed_PluginId_To_TerminalId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
