// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Activity_AddedClientVisibility : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Activity_AddedClientVisibility));
        
        string IMigrationMetadata.Id
        {
            get { return "201602141601318_Activity_AddedClientVisibility"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
