// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Move_Profile_To_Fr8Account : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Move_Profile_To_Fr8Account));
        
        string IMigrationMetadata.Id
        {
            get { return "201605102018494_Move_Profile_To_Fr8Account"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
