using System;
using Fr8Data.Manifests;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Fr8Data.States;

namespace Fr8Data.Crates
{
    [JsonConverter(typeof(DenySerializationConverter), "Crate can't be directly serialized to JSON. Convert it to CrateDTO.")]
    public class Crate
    {
        /**********************************************************************************/
        // Declarations
        /**********************************************************************************/

        private readonly CrateManifestType _manifestType;
        protected object KnownContent;
        private JToken _rawContent;

        /**********************************************************************************/

        public readonly string Id;
        
        /**********************************************************************************/

        public string Label { get; set; }

        public string SourceActivityId { get; set; }

        public AvailabilityType Availability { get; set; }

        /**********************************************************************************/
        /// <summary>
        /// Returns if crate's content is belong to registered manifest types
        /// </summary>
        public bool IsKnownManifest
        {
            get { return KnownContent != null; }
        }

        /**********************************************************************************/

        public CrateManifestType ManifestType
        {
            get { return _manifestType; }
        }

        /**********************************************************************************/
        // Functions
        /**********************************************************************************/
        /// <summary>
        /// Crate new crate with specified manifest type and Id.
        /// </summary>
        /// <param name="manifestType"></param>
        /// <param name="id"></param>
        public Crate(CrateManifestType manifestType, string id)
        {
            _manifestType = manifestType;
            Id = id;
        }

         /// <summary>
        /// Crate new crate with specified manifest type, Id and availability.
        /// </summary>
        /// <param name="manifestType"></param>
        /// <param name="id"></param>
        /// <param name="availability">Crate availability</param>
        public Crate(CrateManifestType manifestType, string id, AvailabilityType availability)
        {
            _manifestType = manifestType;
            Id = id;
            Availability = availability;
        }       
        /**********************************************************************************/
        /// <summary>
        /// Crate new crate with specified manifest type and autogenerated Id
        /// </summary>
        /// <param name="manifestType"></param>
        public Crate(CrateManifestType manifestType)
        {
            _manifestType = manifestType;
            Id = Guid.NewGuid().ToString();
        }

        /**********************************************************************************/
        /// <summary>
        /// Create new create from content. Manifest type is deduced from the content. 
        /// There is no compile-time checks for content's correctness. If manifest type can't be deduced from the content, then run-time error will be throwm.
        /// </summary>
        /// <param name="content"></param>
        /// <returns></returns>
        public static Crate FromContentUnsafe(object content)
        {
            return new Crate(GetManifest(content))
            {
                KnownContent = content
            };
        }

        /**********************************************************************************/
        /// <summary>
        /// Create new create from content. Manifest type is deduced from the content. This method guaranties than manifest type can be correctly deduced
        /// </summary>
        /// <param name="label"></param>
        /// <param name="content"></param>
        /// <returns></returns>
        public static Crate FromContent(string label, Manifest content, AvailabilityType availability = AvailabilityType.NotSet)
        {
            return new Crate(GetManifest(content))
            {
                Label =  label,
                KnownContent = content,
                Availability = availability
            };
        }

        /**********************************************************************************/
        /// <summary>
        /// Create new create from content. Manifest type is deduced from the content. This method guaranties than manifest type can be correctly deduced
        /// </summary>
        /// <param name="label"></param>
        /// <param name="content"></param>
        /// <returns></returns>
        public static Crate<T> FromContent<T>(string label, T content)
        {
            return Crate<T>.FromContent(label, content);
        }

        /**********************************************************************************/
        /// <summary>
        /// Create new create from content. Manifest type is deduced from the content. 
        /// There is no compile-time checks for content's correctness. If manifest type can't be deduced from the content, then run-time error will be throwm.
        /// </summary>
        /// <param name="label"></param>
        /// <param name="content"></param>
        /// <returns></returns>
        public static Crate FromContentUnsafe(string label, object content, AvailabilityType availability = AvailabilityType.NotSet)
        {
            return new Crate(GetManifest(content))
            {
                Label = label,
                KnownContent = content,
                Availability = availability
            };
        }
        
        /**********************************************************************************/
        /// <summary>
        /// Create new crate from JSON with unknown manifest type.
        /// </summary>
        /// <param name="label"></param>
        /// <param name="content"></param>
        /// <returns></returns>
        public static Crate FromJson(string label, JToken content)
        {
            return new Crate(CrateManifestType.Unknown)
            {
                Label = label,
                _rawContent = content
            };
        }

        /**********************************************************************************/
        /// <summary>
        /// Create new crate from JSON with specified manifest tyype.
        /// </summary>
        /// <param name="manifestType"></param>
        /// <param name="content"></param>
        /// <returns></returns>
        public static Crate FromJson(CrateManifestType manifestType, JToken content)
        {
            return new Crate(manifestType)
            {
                _rawContent = content
            };
        }

        /**********************************************************************************/

        internal static Crate FromJson(CrateManifestType manifestType, string id, JToken content)
        {
            return new Crate(manifestType, id)
            {
                _rawContent = content
            };
        }

        /**********************************************************************************/

        internal static Crate FromContent(object content, string id)
        {
            return new Crate(GetManifest(content), id)
            {
                KnownContent = content
            };
        }
      

        /**********************************************************************************/
        /// <summary>
        /// Put content into the crate. This method performs run-time check for content's manifest type correctness
        /// </summary>
        /// <param name="content"></param>
        public void Put(object content)
        {
            if (GetManifest(content) != ManifestType)
            {
                throw new ArgumentException("Content manifest is not compatible with crate manifest", "content");
            }

            KnownContent = content;
            _rawContent = null;
        }

        /**********************************************************************************/
        /// <summary>
        /// Returns JSON content of the crate if any. 
        /// </summary>
        /// <returns></returns>
        public JToken GetRaw()
        {
            return _rawContent;
        }

        /**********************************************************************************/
        /// <summary>
        /// Check if the crate's manifest type is compatible with given Manifest
        /// </summary>
        /// <typeparam name="T">Type of mainifest</typeparam>
        /// <returns></returns>
        public bool IsOfType<T>()
        {
            CrateManifestType manifestType;

            if (!ManifestTypeCache.TryResolveManifest(typeof(T), out manifestType))
            {
                return false;
            }

            return ManifestType == manifestType;
        }

        /**********************************************************************************/
        /// <summary>
        /// Return crate's content
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <returns></returns>
        public T Get<T>() 
        {
            return (T)KnownContent;
        }

        /**********************************************************************************/
        /// <summary>
        /// Return crate's content
        /// </summary>
        /// <returns></returns>
        public object Get()
        {
            return KnownContent;
        }

        /**********************************************************************************/

        public override string ToString()
        {
            return string.Format("{1} [{0}]", Id, Label);
        }

        /**********************************************************************************/

        private static CrateManifestType GetManifest(object content)
        {
            CrateManifestType manifestType;

            if (!ManifestTypeCache.TryResolveManifest(content, out manifestType))
            {
                throw new ArgumentException("Content is not marked with CrateManifestAttribute", "content");
            }

            return manifestType;
        }

        /**********************************************************************************/
    }
}