// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace ShnexyTest
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// CreateNewEventInCalendar - Use 'CreateNewEventInCalendarParams' to pass parameters into this method.
        /// </summary>
        public void CreateNewEventInCalendar()
        {
            #region Variable Declarations
            WinEdit uIAddressandsearchbarEdit = this.UIKwasantGoogleChromeWindow.UIAddressandsearchbarGroup.UIAddressandsearchbarEdit;
            WinClient uIChromeLegacyWindowClient = this.UIKwasantGoogleChromeWindow.UIChromeLegacyWindowWindow.UIChromeLegacyWindowClient;
            WinClient uIChromeLegacyWindowClient1 = this.UIKwasantGoogleChromeWindow.UIChromeLegacyWindowWindow1.UIChromeLegacyWindowClient;
            WinClient uIChromeLegacyWindowClient2 = this.UIKwasantGoogleChromeWindow.UIChromeLegacyWindowWindow2.UIChromeLegacyWindowClient;
            #endregion

            // Type 'localhost:50613/Admin/Index' in 'Address and search bar' text box
            uIAddressandsearchbarEdit.Text = this.CreateNewEventInCalendarParams.UIAddressandsearchbarEditText;

            // Type '{Enter}' in 'Address and search bar' text box
            Keyboard.SendKeys(uIAddressandsearchbarEdit, this.CreateNewEventInCalendarParams.UIAddressandsearchbarEditSendKeys, ModifierKeys.None);

            // Click 'Chrome Legacy Window' client
            Mouse.Click(uIChromeLegacyWindowClient, new Point(554, 138));

            // Click 'Chrome Legacy Window' client
            Mouse.Click(uIChromeLegacyWindowClient, new Point(1397, 203));

            // Click 'Chrome Legacy Window' client
            Mouse.Click(uIChromeLegacyWindowClient, new Point(1047, 354));

            // Click 'Chrome Legacy Window' client
            Mouse.Click(uIChromeLegacyWindowClient, new Point(1047, 354));

            // Type 'This is a test location{Tab}{Tab}{Tab}{Tab}This is a test description{Tab}{Tab}{Tab}This is a test summary.' in 'Address and search bar' text box
            Keyboard.SendKeys(uIAddressandsearchbarEdit, this.CreateNewEventInCalendarParams.UIAddressandsearchbarEditSendKeys1, ModifierKeys.None);

            // Move 'Chrome Legacy Window' client
            Mouse.StartDragging(uIChromeLegacyWindowClient, new Point(1294, 264));
            Mouse.StopDragging(uIChromeLegacyWindowClient, -3, 322);

            // Click 'Chrome Legacy Window' client
            Mouse.Click(uIChromeLegacyWindowClient, new Point(892, 922));

            // Click 'Chrome Legacy Window' client
            Mouse.Click(uIChromeLegacyWindowClient, new Point(1129, 345));

            // Type 'localhost:50613/Admin/Index' in 'Address and search bar' text box
            uIAddressandsearchbarEdit.Text = this.CreateNewEventInCalendarParams.UIAddressandsearchbarEditText1;

            // Type '{Enter}' in 'Address and search bar' text box
            Keyboard.SendKeys(uIAddressandsearchbarEdit, this.CreateNewEventInCalendarParams.UIAddressandsearchbarEditSendKeys2, ModifierKeys.None);

            // Click 'Chrome Legacy Window' client
            Mouse.Click(uIChromeLegacyWindowClient1, new Point(583, 139));

            // Click 'Chrome Legacy Window' client
            Mouse.Click(uIChromeLegacyWindowClient1, new Point(1394, 202));

            // Click 'Chrome Legacy Window' client
            Mouse.Click(uIChromeLegacyWindowClient1, new Point(989, 381));

            // Click 'Chrome Legacy Window' client
            Mouse.Click(uIChromeLegacyWindowClient1, new Point(990, 380));

            // Type '{RShiftKey}this is a test location{Tab}{Tab}{Tab}{Tab}This is a test description{Tab}{Tab}{Tab}this is a test summary' in 'Address and search bar' text box
            Keyboard.SendKeys(uIAddressandsearchbarEdit, this.CreateNewEventInCalendarParams.UIAddressandsearchbarEditSendKeys3, ModifierKeys.None);

            // Move 'Chrome Legacy Window' client
            Mouse.StartDragging(uIChromeLegacyWindowClient1, new Point(1296, 348));
            Mouse.StopDragging(uIChromeLegacyWindowClient1, 3, 252);

            // Click 'Chrome Legacy Window' client
            Mouse.Click(uIChromeLegacyWindowClient1, new Point(885, 922));

            // Click 'Chrome Legacy Window' client
            Mouse.Click(uIChromeLegacyWindowClient1, new Point(1116, 372));

            // Type 'localhost:50613/Admin/Index' in 'Address and search bar' text box
            uIAddressandsearchbarEdit.Text = this.CreateNewEventInCalendarParams.UIAddressandsearchbarEditText2;

            // Type '{Enter}' in 'Address and search bar' text box
            Keyboard.SendKeys(uIAddressandsearchbarEdit, this.CreateNewEventInCalendarParams.UIAddressandsearchbarEditSendKeys4, ModifierKeys.None);

            // Click 'Chrome Legacy Window' client
            Mouse.Click(uIChromeLegacyWindowClient2, new Point(556, 139));

            // Click 'Chrome Legacy Window' client
            Mouse.Click(uIChromeLegacyWindowClient2, new Point(1394, 201));

            // Click 'Chrome Legacy Window' client
            Mouse.Click(uIChromeLegacyWindowClient2, new Point(1001, 318));

            // Click 'Chrome Legacy Window' client
            Mouse.Click(uIChromeLegacyWindowClient2, new Point(1008, 320));

            // Type 'This is a test location{Tab}{Tab}{Tab}{Tab}This is a test description{Tab}{Tab}{Tab}This is a test summary' in 'Address and search bar' text box
            Keyboard.SendKeys(uIAddressandsearchbarEdit, this.CreateNewEventInCalendarParams.UIAddressandsearchbarEditSendKeys5, ModifierKeys.None);

            // Click 'Chrome Legacy Window' client
            Mouse.Click(uIChromeLegacyWindowClient2, new Point(898, 842));

            // Click 'Chrome Legacy Window' client
            Mouse.Click(uIChromeLegacyWindowClient2, new Point(1088, 243));
        }
        
        #region Properties
        public virtual CreateNewEventInCalendarParams CreateNewEventInCalendarParams
        {
            get
            {
                if ((this.mCreateNewEventInCalendarParams == null))
                {
                    this.mCreateNewEventInCalendarParams = new CreateNewEventInCalendarParams();
                }
                return this.mCreateNewEventInCalendarParams;
            }
        }
        
        public UIKwasantGoogleChromeWindow UIKwasantGoogleChromeWindow
        {
            get
            {
                if ((this.mUIKwasantGoogleChromeWindow == null))
                {
                    this.mUIKwasantGoogleChromeWindow = new UIKwasantGoogleChromeWindow();
                }
                return this.mUIKwasantGoogleChromeWindow;
            }
        }
        #endregion
        
        #region Fields
        private CreateNewEventInCalendarParams mCreateNewEventInCalendarParams;
        
        private UIKwasantGoogleChromeWindow mUIKwasantGoogleChromeWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'CreateNewEventInCalendar'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class CreateNewEventInCalendarParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'localhost:50613/Admin/Index' in 'Address and search bar' text box
        /// </summary>
        public string UIAddressandsearchbarEditText = "localhost:50613/Admin/Index";
        
        /// <summary>
        /// Type '{Enter}' in 'Address and search bar' text box
        /// </summary>
        public string UIAddressandsearchbarEditSendKeys = "{Enter}";
        
        /// <summary>
        /// Type 'This is a test location{Tab}{Tab}{Tab}{Tab}This is a test description{Tab}{Tab}{Tab}This is a test summary.' in 'Address and search bar' text box
        /// </summary>
        public string UIAddressandsearchbarEditSendKeys1 = "This is a test location{Tab}{Tab}{Tab}{Tab}This is a test description{Tab}{Tab}{T" +
            "ab}This is a test summary.";
        
        /// <summary>
        /// Type 'localhost:50613/Admin/Index' in 'Address and search bar' text box
        /// </summary>
        public string UIAddressandsearchbarEditText1 = "localhost:50613/Admin/Index";
        
        /// <summary>
        /// Type '{Enter}' in 'Address and search bar' text box
        /// </summary>
        public string UIAddressandsearchbarEditSendKeys2 = "{Enter}";
        
        /// <summary>
        /// Type '{RShiftKey}this is a test location{Tab}{Tab}{Tab}{Tab}This is a test description{Tab}{Tab}{Tab}this is a test summary' in 'Address and search bar' text box
        /// </summary>
        public string UIAddressandsearchbarEditSendKeys3 = "{RShiftKey}this is a test location{Tab}{Tab}{Tab}{Tab}This is a test description{" +
            "Tab}{Tab}{Tab}this is a test summary";
        
        /// <summary>
        /// Type 'localhost:50613/Admin/Index' in 'Address and search bar' text box
        /// </summary>
        public string UIAddressandsearchbarEditText2 = "localhost:50613/Admin/Index";
        
        /// <summary>
        /// Type '{Enter}' in 'Address and search bar' text box
        /// </summary>
        public string UIAddressandsearchbarEditSendKeys4 = "{Enter}";
        
        /// <summary>
        /// Type 'This is a test location{Tab}{Tab}{Tab}{Tab}This is a test description{Tab}{Tab}{Tab}This is a test summary' in 'Address and search bar' text box
        /// </summary>
        public string UIAddressandsearchbarEditSendKeys5 = "This is a test location{Tab}{Tab}{Tab}{Tab}This is a test description{Tab}{Tab}{T" +
            "ab}This is a test summary";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIKwasantGoogleChromeWindow : WinWindow
    {
        
        public UIKwasantGoogleChromeWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Kwasant - Google Chrome";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Chrome_WidgetWin_1";
            this.WindowTitles.Add("Kwasant - Google Chrome");
            this.WindowTitles.Add("- Kwasant - Google Chrome");
            this.WindowTitles.Add("Index - Kwasant - Google Chrome");
            this.WindowTitles.Add("Event - Kwasant - Google Chrome");
            #endregion
        }
        
        #region Properties
        public UIAddressandsearchbarGroup UIAddressandsearchbarGroup
        {
            get
            {
                if ((this.mUIAddressandsearchbarGroup == null))
                {
                    this.mUIAddressandsearchbarGroup = new UIAddressandsearchbarGroup(this);
                }
                return this.mUIAddressandsearchbarGroup;
            }
        }
        
        public UIChromeLegacyWindowWindow UIChromeLegacyWindowWindow
        {
            get
            {
                if ((this.mUIChromeLegacyWindowWindow == null))
                {
                    this.mUIChromeLegacyWindowWindow = new UIChromeLegacyWindowWindow(this);
                }
                return this.mUIChromeLegacyWindowWindow;
            }
        }
        
        public UIChromeLegacyWindowWindow1 UIChromeLegacyWindowWindow1
        {
            get
            {
                if ((this.mUIChromeLegacyWindowWindow1 == null))
                {
                    this.mUIChromeLegacyWindowWindow1 = new UIChromeLegacyWindowWindow1(this);
                }
                return this.mUIChromeLegacyWindowWindow1;
            }
        }
        
        public UIChromeLegacyWindowWindow2 UIChromeLegacyWindowWindow2
        {
            get
            {
                if ((this.mUIChromeLegacyWindowWindow2 == null))
                {
                    this.mUIChromeLegacyWindowWindow2 = new UIChromeLegacyWindowWindow2(this);
                }
                return this.mUIChromeLegacyWindowWindow2;
            }
        }
        #endregion
        
        #region Fields
        private UIAddressandsearchbarGroup mUIAddressandsearchbarGroup;
        
        private UIChromeLegacyWindowWindow mUIChromeLegacyWindowWindow;
        
        private UIChromeLegacyWindowWindow1 mUIChromeLegacyWindowWindow1;
        
        private UIChromeLegacyWindowWindow2 mUIChromeLegacyWindowWindow2;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIAddressandsearchbarGroup : WinGroup
    {
        
        public UIAddressandsearchbarGroup(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "Address and search bar";
            this.WindowTitles.Add("Kwasant - Google Chrome");
            this.WindowTitles.Add("Event - Kwasant - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinEdit UIAddressandsearchbarEdit
        {
            get
            {
                if ((this.mUIAddressandsearchbarEdit == null))
                {
                    this.mUIAddressandsearchbarEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIAddressandsearchbarEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Address and search bar";
                    this.mUIAddressandsearchbarEdit.WindowTitles.Add("Kwasant - Google Chrome");
                    this.mUIAddressandsearchbarEdit.WindowTitles.Add("Event - Kwasant - Google Chrome");
                    #endregion
                }
                return this.mUIAddressandsearchbarEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIAddressandsearchbarEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIChromeLegacyWindowWindow : WinWindow
    {
        
        public UIChromeLegacyWindowWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "205757888";
            this.WindowTitles.Add("- Kwasant - Google Chrome");
            this.WindowTitles.Add("Index - Kwasant - Google Chrome");
            this.WindowTitles.Add("Event - Kwasant - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinClient UIChromeLegacyWindowClient
        {
            get
            {
                if ((this.mUIChromeLegacyWindowClient == null))
                {
                    this.mUIChromeLegacyWindowClient = new WinClient(this);
                    #region Search Criteria
                    this.mUIChromeLegacyWindowClient.SearchProperties[WinControl.PropertyNames.Name] = "Chrome Legacy Window";
                    this.mUIChromeLegacyWindowClient.WindowTitles.Add("- Kwasant - Google Chrome");
                    this.mUIChromeLegacyWindowClient.WindowTitles.Add("Index - Kwasant - Google Chrome");
                    this.mUIChromeLegacyWindowClient.WindowTitles.Add("Event - Kwasant - Google Chrome");
                    #endregion
                }
                return this.mUIChromeLegacyWindowClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIChromeLegacyWindowClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIChromeLegacyWindowWindow1 : WinWindow
    {
        
        public UIChromeLegacyWindowWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "315783936";
            this.WindowTitles.Add("- Kwasant - Google Chrome");
            this.WindowTitles.Add("Index - Kwasant - Google Chrome");
            this.WindowTitles.Add("Event - Kwasant - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinClient UIChromeLegacyWindowClient
        {
            get
            {
                if ((this.mUIChromeLegacyWindowClient == null))
                {
                    this.mUIChromeLegacyWindowClient = new WinClient(this);
                    #region Search Criteria
                    this.mUIChromeLegacyWindowClient.SearchProperties[WinControl.PropertyNames.Name] = "Chrome Legacy Window";
                    this.mUIChromeLegacyWindowClient.WindowTitles.Add("- Kwasant - Google Chrome");
                    this.mUIChromeLegacyWindowClient.WindowTitles.Add("Index - Kwasant - Google Chrome");
                    this.mUIChromeLegacyWindowClient.WindowTitles.Add("Event - Kwasant - Google Chrome");
                    #endregion
                }
                return this.mUIChromeLegacyWindowClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIChromeLegacyWindowClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIChromeLegacyWindowWindow2 : WinWindow
    {
        
        public UIChromeLegacyWindowWindow2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "329980672";
            this.WindowTitles.Add("- Kwasant - Google Chrome");
            this.WindowTitles.Add("Index - Kwasant - Google Chrome");
            this.WindowTitles.Add("Event - Kwasant - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinClient UIChromeLegacyWindowClient
        {
            get
            {
                if ((this.mUIChromeLegacyWindowClient == null))
                {
                    this.mUIChromeLegacyWindowClient = new WinClient(this);
                    #region Search Criteria
                    this.mUIChromeLegacyWindowClient.SearchProperties[WinControl.PropertyNames.Name] = "Chrome Legacy Window";
                    this.mUIChromeLegacyWindowClient.WindowTitles.Add("- Kwasant - Google Chrome");
                    this.mUIChromeLegacyWindowClient.WindowTitles.Add("Index - Kwasant - Google Chrome");
                    this.mUIChromeLegacyWindowClient.WindowTitles.Add("Event - Kwasant - Google Chrome");
                    #endregion
                }
                return this.mUIChromeLegacyWindowClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIChromeLegacyWindowClient;
        #endregion
    }
}
